### ISSUE TITLE
g++ compile error in grammar.yacc.cc under Ubuntu 20.10

### ISSUE THREAD

**Issue by jdykstra** [jdykstra/ucsd-psystem-xc#1]
g++  -g -O2 -I. -c lib/pascal/grammar.yacc.cc
y.tab.c:156:28: error: ‘pascal_grammar_error’ redeclared as different kind of entity
In file included from lib/pascal/grammar.y:32:
./lib/pascal/lex.h:51:6: note: previous declaration ‘void pascal_grammar_error(const char*)’
   51 | void pascal_grammar_error(const char *text);
      |      ^~~~~~~~~~~~~~~~~~~~

**Comment by jdykstra** [comment]
Worked with bison 3.5.1 in Ubuntu 20.04.  Failing with bison 3.7.

Fixed the namespace collision on pascal_grammar_error(), but still have:

g++  -g -O2 -I. -c lib/pascal/grammar.yacc.cc
lib/pascal/grammar.y: In function ‘int pascal_grammar_parse()’:
lib/pascal/grammar.y:452:61: error: expression cannot be used as a function
  452 |         { yyerror("that \":=\" should be \"=\""); }
      |                                                             ^
lib/pascal/grammar.y:454:60: error: expression cannot be used as a function
  454 |         { yyerror("that \":\" should be \"=\""); }
      |                                                            ^
lib/pascal/grammar.y:485:60: error: expression cannot be used as a function
  485 |         { yyerror("that \"=\" should be \":\""); }
      |                                                            ^
lib/pascal/grammar.y:487:61: error: expression cannot be used as a function
  487 |         { yyerror("that \":=\" should be \":\""); }
      |                                                             ^
lib/pascal/grammar.y:537:47: error: expression cannot be used as a function
  537 |         { yyerror("missing comma"); }
      |                                               ^
lib/pascal/grammar.y:590:66: error: expression cannot be used as a function
  590 |             yyerror("packed files are not supported");
      |                                                                  ^
lib/pascal/grammar.y:895:17: error: expression cannot be used as a function
  895 |                 );
      |                 ^
lib/pascal/grammar.y:909:80: error: expression cannot be used as a function
  909 |                 yyerror("must specify a return type for functions");
      |                                                                                ^
lib/pascal/grammar.y:913:81: error: expression cannot be used as a function
  913 |             yyerror("must not specify a return type for procedures");
      |                                                                                 ^
lib/pascal/grammar.y:1392:13: error: expression cannot be used as a function
 1392 |             );
      |             ^
lib/pascal/grammar.y:1465:13: error: expression cannot be used as a function
 1465 |             );
      |             ^
lib/pascal/grammar.y:1817:80: error: expression cannot be used as a function
 1817 |             yyerror("there should be no colon after \"otherwise\"");
      |                                                                                ^
y.tab.c:4647:61: error: expression cannot be used as a function
y.tab.c:4758:61: error: expression cannot be used as a function
make: *** [Makefile:1764: lib/pascal/grammar.yacc.o] Error 1

Peter's lex.cc doesn't provide yyerror(), which the bison documentation says it should.  But that's been true for a long time.  Something is happening with bison I don't understand yet.

**Comment by jdykstra** [comment]
Closed by 3fa1e8cd61584e28092972e05832cdf925aa8f6b.
